CREATE OR ALTER FUNCTION [DBO].[CONVERT_INT_TO_DATE] (@V INT)
    RETURNS DATE
AS
BEGIN
    DECLARE @DATE DATE

    SET @DATE = DATEFROMPARTS(@V / 10000, (@V % 10000) / 100, @V % 100)

    RETURN @DATE
END