CREATE OR ALTER FUNCTION [dbo].[CONVERT_INT_TO_DATETIME] (@V INT)
    RETURNS DATETIME
AS
BEGIN
    DECLARE @DATETIME DATETIME

    SET @DATETIME = CONVERT(DATETIME, CONVERT(VARCHAR(8), @V))
    
    RETURN @DATETIME
END