CREATE OR ALTER FUNCTION [DBO].[PAD_LEFT]
(
	@TEXT_PAD    VARCHAR(8000),
	@CHAR_TO_PAD VARCHAR(1),
	@NUM_TO_PAD   INT
)
RETURNS VARCHAR(8000)
AS
BEGIN
 DECLARE @OUTPUT VARCHAR(8000);

 SET @OUTPUT = REPLICATE(@CHAR_TO_PAD, @NUM_TO_PAD) + @TEXT_PAD;

 RETURN RIGHT(@OUTPUT, @NUM_TO_PAD);
END